name: Homebrew Release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version
        id: get_version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT
          else
            echo "VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
          fi

      - name: Download Release Assets
        run: |
          mkdir -p dist
          cd dist
          curl -L -o gcx_${{ steps.get_version.outputs.VERSION }}_darwin_amd64.tar.gz https://github.com/sxwebdev/gcx/releases/download/${{ steps.get_version.outputs.VERSION }}/gcx_${{ steps.get_version.outputs.VERSION }}_darwin_amd64.tar.gz
          curl -L -o gcx_${{ steps.get_version.outputs.VERSION }}_darwin_arm64.tar.gz https://github.com/sxwebdev/gcx/releases/download/${{ steps.get_version.outputs.VERSION }}/gcx_${{ steps.get_version.outputs.VERSION }}_darwin_arm64.tar.gz

      - name: Update Homebrew Formula
        uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          formula-name: gcx
          homebrew-tap: sxwebdev/homebrew-tap
          download-url: |
            https://github.com/sxwebdev/gcx/releases/download/${{ steps.get_version.outputs.VERSION }}/gcx_${{ steps.get_version.outputs.VERSION }}_darwin_amd64.tar.gz
            https://github.com/sxwebdev/gcx/releases/download/${{ steps.get_version.outputs.VERSION }}/gcx_${{ steps.get_version.outputs.VERSION }}_darwin_arm64.tar.gz
          commit-message: "chore: bump gcx to ${{ steps.get_version.outputs.VERSION }}"
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
